wifi:
  id: wifi_id
  on_connect:
    - led_ring_controller.set_flag:
        flag: improv_ble
        value: false
    - led_ring_controller.set_flag:
        flag: network_ok
        value: !lambda return id(wifi_id).is_connected() && id(api_id).is_connected();
  on_disconnect:
    - led_ring_controller.set_flag:
        flag: network_ok
        value: false

improv_serial:

